// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJBn8NcEH-FOSm3z9z5VCLBKpjKlqz6qk',
    appId: '1:485112814779:web:e611a5c7a1d7f262765d9e',
    messagingSenderId: '485112814779',
    projectId: 'iter-zero',
    authDomain: 'iter-zero.firebaseapp.com',
    storageBucket: 'iter-zero.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqT_AcTtS7KT0M22NjIeb2cEjMNx3Q6_Q',
    appId: '1:485112814779:android:eb7c0581629f7058765d9e',
    messagingSenderId: '485112814779',
    projectId: 'iter-zero',
    storageBucket: 'iter-zero.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Mjwct7BpPuPXhLMYmX6w-0hcMQv2o0U',
    appId: '1:485112814779:ios:d051fefb30790ccb765d9e',
    messagingSenderId: '485112814779',
    projectId: 'iter-zero',
    storageBucket: 'iter-zero.firebasestorage.app',
    iosBundleId: 'com.csc318.connectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Mjwct7BpPuPXhLMYmX6w-0hcMQv2o0U',
    appId: '1:485112814779:ios:d051fefb30790ccb765d9e',
    messagingSenderId: '485112814779',
    projectId: 'iter-zero',
    storageBucket: 'iter-zero.firebasestorage.app',
    iosBundleId: 'com.csc318.connectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJBn8NcEH-FOSm3z9z5VCLBKpjKlqz6qk',
    appId: '1:485112814779:web:d34e9b5b727e14e1765d9e',
    messagingSenderId: '485112814779',
    projectId: 'iter-zero',
    authDomain: 'iter-zero.firebaseapp.com',
    storageBucket: 'iter-zero.firebasestorage.app',
  );
}
